Remove extra SELECT in db.getBSOs to test for pagination
mozilla-services/go-syncstorage pull request #168
Opened 2017-05-03 00:26 UTC by mostlygeek

On @rfk's advice the extra SELECT is unnecessary. It is faster and
more elegant to ask for LIMIT+1 rows to test for pagination.

2017-05-03 01:37 UTC, rfk requested changes
The logic looks sound to me, except for the special case of `?limit=0`.  Nobody should be doing that, but it's worth making sure it still works correctly in order to ensure the API is consistent.

2017-05-03 01:37 UTC, rfk commented on syncstorage/db.go
> +	}
Will this do the right thin in the case of `limit=0` on a collection with no items?  Or, should the conditional here be `limit >=0`?

2017-05-03 01:37 UTC, rfk commented on syncstorage/db.go
> +		bsos = bsos[:num-1]
ditto here re: handling of `limit=0`, which nobody should ever use, but which we should probably not break.  Perhaps we need explicit functional tests cases for this case?

2017-05-03 14:35 UTC, mostlygeek commented on syncstorage/db.go
> +	}
Good point. I suppose a client should be able to send limit=0 to get a 0 byte body but information if there are records actually to download. 

So a limit=0 should return an X-Weave-Next-Offset header.

2017-05-04 02:42 UTC, rfk approved these changes
LGTM!

2017-05-04 17:00 UTC, merged